#!/bin/zsh
##? autoload-dir - autoload all function files in specified directory.

defun autoload-dir() {
    [[ -d "$1" ]] || return 1

    # set in paths
    fpath=( ${1:q}/{,**/*(/FN)} $fpath)

    # define functions autoloaded
    {
	defun _ignore() {
	    case ${_name} in
		"*\~")    ;&
		"*\~bak") ;&
		"*\~*\~")  return 0;;
		*)       return 1;;
	    esac
	}

	local _paths=( ${1:q}/**/*(.N) )
	local _name
	for _name in ${_paths:t}; do
	    _ignore &&
		continue
            autoload -Uz ${_name}
	done
    }
}

autoload-dir ${@}
