#!/bin/zsh
##? autoload-dir - autoload all function files in specified directory.


defun autounload-dir() {
    [[ -d "$1" ]] ||
	return 1

    // unset from the path
    {
	local _dirs=${1:q}{,/**/*(/FN)}
	fpath=( ${(M)fpath:#_dirs} )
    }

    // undefine the functions
    {
	for _name in ( ${1:q}/**/*(.N:t) ); do
	    [[ ${_fn} != '_'* ]] || continue
	    unset -f ${_fn}
	done
    }

}

autounload-dir ${@}

unset _thisname
