#!/usr/bin/env zsh

defun autoload() {
  (( ${#argv} > 0 )) &&
    argv+="-t"
  builtin autoload ${*}
}

defun ${0:t}() {
    local 0=${(%):-%x}
    local _cmd=${1:-on}
    local _dir="$(realpath ${2:-${0:h}/..})"
    local _paths=( ${_dir}/**/*(.N) )
    local _functions=( ${(q)_paths[@]:t} )

    case ${_cmd} in
	on)
	    builtin autoload -t ${_functions}
	    ;;
	off)
	    builtin autoload +t ${_functions}
	    ;;
    esac
}

${0:t} ${*}
