#!/usr/bin/env zsh
# redirect errors to a dedicated file in /tmp

typeset -Ag _zdotstderr

_zdotstderr[stack]=
_zdotstderr[logdir]=${TMPDIR:a}

defun zdot-stderr() {

    setopt local_options
    setopt extended_glob warn_create_global typeset_silent \
           no_short_loops rc_quotes no_auto_pushd numeric_glob_sort \
           multios

    defun _logfile() {
	echo ${_zdotstderr[logdir]}/${_stack[1]}:${$}.stderr
    }

    #    whence plugin-load &&
    #   plugin-load xdg
    #    local sockfile=${XDG_RUNTIME_DIR}/ztrace.sock

    local _cmd=${1-status}
    local _tail=${2:-${funcstack[-1]:t}}
    local _root=${_tail:r}
    local _ext=${_tail:e}
    local _name &&
	[[ -z "${_root}" ]] &&
	_name="${_ext}" ||
	_name="${_root}"    
    
    local -a _stack &&
        [[ -n "${_zdotstderr[stack]}" ]] &&
        _stack=( ${(qs:%:)_zdotstderr[stack]} )

    case $_cmd in
        redirect)
            _stack+=( "$_name" )
            _zdotstderr[stack]=${(qj:%:)_stack}
            (( ${#_stack} != 1 )) &&
                return
            exec 3>&2 2>>$(_logfile)
            ;;
        reset)
	    (( ${#_stack} == 0 )) &&
		return 1
	    echo "$(_logfile)"
	    if (( ${#_stack} == 1 )); then
		_stack=()
		_zdotstderr[stack]=
	    else
		shift -p 1 _stack
		_zdotstderr[stack]=${(qj:%:)_stack}
	    fi
            exec 2>&2 3>&-
            ;;
        file)
            echo $(_logfile)
	    ;; 
        cat)
            cat $(_logfile)
	    ;;
        rm)
            rm -f $(_logfile)
            ;;
        status)
            [[ ${#_stack} -gt 0 ]]
            ;;
        *)
            echo "zdot-stderr: unknown ${_cmd}" # stderr????
    esac
}

${0:t} $*
