#!/usr/bin/env zsh

[[ -z "${ZDOTDEBUG:-}" ]] && return 1

local _cmd=${1:-leave}

case ${_cmd} in
  enter)
    zdot-stderr redirect
    zdot-trace on
    ;;
  leave)
    zdot-trace off
    zdot-stderr reset
    ;;
esac
